name: coverage_viewer
description: A simple and elegant tool to visualize Dart and Flutter test coverage reports
version: 0.0.1
repository: https://github.com/jorgemvv01/coverage_viewer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  args: ^2.4.0
  path: ^1.9.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  coverage_viewer: